"""Smoke test for the v3 MLX 4-bit model. Runs a few canonical prompts and prints
the cleaned (think-stripped) output so we can see whether v3 behaves correctly.

Run from project root:
  python scripts/inference/smoke_test_v3.py
"""
from __future__ import annotations

import argparse
import re
import sys
import time
from pathlib import Path

from mlx_lm import generate, load


SYSTEM_PROMPT = """# Role
You are a mathematical statement judgment and correction engine.

# Task
First decide whether the user's mathematical statement is:
CORRECT, FALSE, INCOMPLETE, GARBLED_BUT_IDENTIFIABLE, or UNCLEAR.

# Output rules
1. You MUST first write a concise internal judgment inside a <think>...</think> block.
2. If CORRECT, output the clean mathematical statement only.
3. If FALSE, output the correct theorem or statement.
4. If INCOMPLETE, output the complete rigorous theorem with missing assumptions.
5. If GARBLED_BUT_IDENTIFIABLE, infer the intended theorem and rewrite it fully.
6. If UNCLEAR, output exactly: Cannot identify the intended theorem.
7. Never repeat malformed mathematical text unchanged.
8. Use standard LaTeX formatting for formulas ($...$ or $$...$$).
"""

UNCLEAR_ZH = "无法识别其意图定理。"
UNCLEAR_EN = "Cannot identify the intended theorem."

CASES = [
    ("CORRECT", "Every differentiable function is continuous.", ["differentiable", "continuous"]),
    ("FALSE", "Every continuous function is differentiable.", ["differentiable", "continuous"]),
    (
        "INCOMPLETE",
        "A continuous function on an interval achieves its maximum and minimum.",
        ["closed", "bounded", "maximum", "minimum"],
    ),
    (
        "GARBLED_BUT_IDENTIFIABLE",
        "Pythagorean: a sqrd plus b sqrd is c sqrd in a right triangle.",
        ["a^2", "b^2", "c^2"],
    ),
    ("UNCLEAR", "Let thing be valid then A iff B maybe with x.", [UNCLEAR_EN]),
    (
        "MULTI_LINE",
        "Proposition 29. Let R be a commutative ring with identity and let I be an ideal of R. Denote\n"
        "by\n"
        "(I) = I[x]\n"
        "the ideal of R[x] generated by I. Then\n"
        "R[x]/(I) ~= (R/I)[x]",
        ["R[x]", "(R/I)[x]"],
    ),
]


def strip_think(text: str) -> str:
    cleaned = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    if "<think>" in cleaned:
        cleaned = cleaned.split("</think>", 1)[-1].strip()
    return cleaned.replace(UNCLEAR_ZH, UNCLEAR_EN)


def run(model_path: str, max_tokens: int) -> int:
    if not Path(model_path).is_dir():
        print(f"[FATAL] Model directory not found: {model_path}", file=sys.stderr)
        return 1

    print(f"[INFO] Loading {model_path}")
    t0 = time.time()
    model, tokenizer = load(model_path)
    print(f"[INFO] Loaded in {time.time() - t0:.1f}s\n")

    failed = 0
    for label, user_input, expected_terms in CASES:
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_input},
        ]
        prompt = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        t0 = time.time()
        raw = generate(model, tokenizer, prompt=prompt, max_tokens=max_tokens, verbose=False)
        cleaned = strip_think(raw)
        elapsed = time.time() - t0

        print("=" * 70)
        print(f"[{label}]  ({elapsed:.1f}s)")
        print(f"  IN:  {user_input!r}")
        print(f"  OUT: {cleaned}")
        if UNCLEAR_ZH in cleaned:
            print("  !! Chinese UNCLEAR phrase leaked through post-processing")
            failed += 1
        if not cleaned:
            print("  !! Empty output")
            failed += 1
        if label not in {"CORRECT", "UNCLEAR"} and cleaned.strip().lower() == user_input.strip().lower():
            print("  !! Output repeats the flawed input unchanged")
            failed += 1
        lowered = cleaned.lower()
        missing_terms = [
            term for term in expected_terms
            if term != UNCLEAR_EN and term.lower() not in lowered
        ]
        if UNCLEAR_EN in expected_terms and cleaned.strip() != UNCLEAR_EN:
            print(f"  !! Expected exact unclear fallback: {UNCLEAR_EN!r}")
            failed += 1
        elif missing_terms:
            print(f"  !! Missing expected term(s): {', '.join(missing_terms)}")
            failed += 1

    print("=" * 70)
    if failed:
        print(f"[RESULT] {failed} issue(s) detected.")
    else:
        print("[RESULT] All cases passed the smoke checks.")
    return 0 if failed == 0 else 2


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--model", default="models/qwen_7b_v3_mlx_q4")
    p.add_argument("--max-tokens", type=int, default=384)
    args = p.parse_args()
    return run(args.model, args.max_tokens)


if __name__ == "__main__":
    sys.exit(main())
