"""
Regenerate the math-correction training set using a strong local "teacher" model.

The original v1 dataset was generated with a hand-written template, so 60%+ of
the <think> blocks were the same string ("The input statement appears to be
related to '<X>'. ... The absolute rigorous form is: <Y>.") and the model
learned to recite the template instead of reasoning. This script replaces that
with real CoT generated by DeepSeek-R1-Distill-Qwen-7B (which natively emits
<think> blocks).

Hardware target: RTX 5060 Laptop 8GB VRAM. Teacher loads in 4-bit (~5GB).

CLI:
  # Full run (8000 samples, ~5h)
  python scripts/data_processing/regenerate_with_teacher.py --target 8000

  # Quick smoke test
  python scripts/data_processing/regenerate_with_teacher.py --dry-run --num 5

  # Resume from previous partial run
  python scripts/data_processing/regenerate_with_teacher.py --target 8000
  # (auto-detects data/student_notes_train_v2_partial.json and skips done ones)
"""

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
import os
import random
import re
import sys
import time
import urllib.error
import urllib.request
from collections import Counter

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

# --------------------------------------------------------------------------- #
# Constants
# --------------------------------------------------------------------------- #

SYSTEM_PROMPT = """# Role
You are a minimalist mathematical theorem engine. Your task is to correct mathematical statements while preserving the user's conversational context.

# Guidelines
1. Logic engine (Hidden CoT): You MUST first wrap your internal reasoning, deductions, and verification of the user's statement inside a <think>...</think> block.
2. Core correction: After thinking, identify the mathematical theorem the user is attempting to state, and replace ONLY the math part with its rigorous, complete form.
3. Garbled text recovery: If the math formulation contains typos or random characters, deduce the intended theorem in your <think> block.
4. Context preservation: If the user includes conversational text (e.g., "I think", "is this right?", "User:"), output that exact conversational text unchanged in its original position outside the <think> block.
5. Zero-fluff AI output: Outside of the <think> block, NEVER add conversational filler or judgments (e.g., "The correct statement is"). Only output the user's text and the corrected theorem.
6. Formatting: Use standard LaTeX formatting for formulas ($...$ or $$...$$).

# Example
Input: "Hey, is it true that every continuous function is d8ff3r%ntiable?"
Output: "<think>
The user asks if continuous implies differentiable. This is mathematically false (Weierstrass function is a counterexample). The correct fundamental theorem relates differentiability to continuity: differentiable implies continuous. I will output the corrected theorem while keeping the user's query wrappers.
</think>
Hey, is it true that every differentiable function is continuous?"
"""

# Diverse conversational wrappers — lowered chance of repetitive prefixes
WRAPPERS_PREFIX = [
    "", "", "", "",  # often no prefix
    "I'm not sure, but is it true that ",
    "Hey, so ",
    "My professor said ",
    "Can you verify if ",
    "Please check: ",
    "Is it correct to assert ",
    "Quick sanity check: ",
    "Wait, ",
    "From my notes, ",
    "Reading a textbook claim: ",
    "Saw on a forum: ",
    "Lecture mentioned ",
    "I keep forgetting — is ",
    "Trying to recall: ",
    "Someone told me ",
    "Hmm, ",
    "OK so ",
    "Question: ",
]

WRAPPERS_SUFFIX = [
    "", "", "", "",
    " What do you think?",
    " Right?",
    "?",
    " (I might be misremembering)",
    " Is that the standard form?",
    " — does that sound complete?",
    " Am I missing a condition?",
    " — please correct if wrong.",
    " Let me know if I'm off.",
    " Sound right to you?",
]

# Quality keywords — at least one must appear in <think> for the sample to count
THINK_QUALITY_KEYWORDS = [
    "because", "however", "counterexample", "by definition",
    "actually", "wait", "wait,", "fails", "hold", "holds",
    "indeed", "specifically", "note that", "recall", "since",
    "so the", "therefore", "but the", "if and only if",
    "in fact", "consider", "for example", "implies",
]

# Non-math probes: model should learn to gracefully decline
NON_MATH_QUERIES = [
    "What's the weather like today?",
    "Hello!",
    "Can you write me a Python function to sort a list?",
    "Tell me a joke.",
    "你好",
    "Translate this sentence to French: I love mathematics.",
    "What time is it?",
    "Recommend me a book.",
    "How do I install Python?",
    "Are you sentient?",
    "Who won the world cup in 2022?",
    "I had a long day at work.",
    "Sing me a song.",
    "What is your name?",
    "Help me write an email to my boss.",
]

# --------------------------------------------------------------------------- #
# Source data
# --------------------------------------------------------------------------- #

# 60 base theorems (copied from generate_student_notes.py — kept inline so
# this script is self-contained)
BASE_THEOREMS = [
    ("Differentiability implies continuity",
     "A differentiable function is continuous."),
    ("Uniform Continuity on Compact Sets",
     "Every continuous function on a closed and bounded interval is uniformly continuous."),
    ("Extreme Value Theorem",
     "A continuous function on a closed and bounded interval achieves its maximum and minimum."),
    ("Monotone Convergence Theorem",
     "If a sequence of real numbers is bounded and monotonic, then it converges."),
    ("Continuity of Differentiable Functions",
     "If $f$ is differentiable at $a$, then $f$ is continuous at $a$."),
    ("Bolzano-Weierstrass Theorem",
     r"Every bounded sequence in $\mathbb{R}^n$ has a convergent subsequence."),
    ("Riemann Integrability of Continuous Functions",
     "If a function is continuous on a closed interval, it is Riemann integrable."),
    ("Differentiation of Power Series",
     "A power series can be differentiated term-by-term within its radius of convergence."),
    ("Divergence Test for Series",
     r"If $\lim_{n \to \infty} a_n \neq 0$, then the series $\sum a_n$ diverges."),
    ("Absolute Convergence Theorem",
     "Absolute convergence implies conditional convergence."),
    ("Fundamental Theorem of Calculus",
     r"If $f$ is continuous on $[a, b]$, then the function $F(x) = \int_a^x f(t) dt$ is differentiable on $(a, b)$ with $F'(x) = f(x)$."),
    ("Mean Value Theorem",
     r"If $f$ is continuous on $[a,b]$ and differentiable on $(a,b)$, there exists $c \in (a,b)$ with $f'(c) = (f(b)-f(a))/(b-a)$."),
    ("Rolle's Theorem",
     "If a function is continuous on a closed interval, differentiable on its interior, and equal at the endpoints, then there is an interior point where its derivative is zero."),
    ("Taylor's Theorem",
     "A $k$-times differentiable function can be approximated near a point by its $k$-th order Taylor polynomial with a remainder term."),
    ("Lebesgue Dominated Convergence Theorem",
     "If a sequence of measurable functions converges pointwise and is dominated by an integrable function, the integral of the limit equals the limit of the integrals."),
    ("Fatou's Lemma",
     "For a sequence of non-negative measurable functions, the integral of the limit inferior is at most the limit inferior of the integrals."),
    ("Cyclic Groups of Prime Order", "A group of prime order is cyclic."),
    ("Cayley's Theorem",
     "Every finite group is isomorphic to a subgroup of a symmetric group."),
    ("Lagrange's Theorem",
     "The order of a subgroup divides the order of the finite group."),
    ("Sylow Theorems",
     r"For every prime power $p^k$ dividing the order of a finite group, a subgroup of order $p^k$ exists."),
    ("First Isomorphism Theorem",
     r"If $\phi: G \to H$ is a group homomorphism, then $G/\ker(\phi) \cong \text{Im}(\phi)$."),
    ("Fields and Integral Domains", "Every finite integral domain is a field."),
    ("Roots of Polynomials",
     "A non-zero polynomial of degree $n$ over a field has at most $n$ distinct roots."),
    ("Fermat's Little Theorem",
     "If $p$ is a prime, then $a^p \\equiv a \\pmod{p}$ for any integer $a$."),
    ("Structure Theorem for Finitely Generated Abelian Groups",
     "Every finitely generated abelian group is isomorphic to a direct product of cyclic groups."),
    ("Basis Existence Theorem", "Every vector space has a basis."),
    ("Rank-Nullity Theorem",
     "For a linear map between finite-dimensional vector spaces, rank + nullity = dimension of the domain."),
    ("Linear Independence of Eigenvectors",
     "Eigenvectors corresponding to distinct eigenvalues are linearly independent."),
    ("Spectral Theorem for Symmetric Matrices",
     "Every real symmetric matrix is orthogonally diagonalizable with real eigenvalues."),
    ("Determinant of Product",
     r"$\det(AB) = \det(A)\det(B)$ for square matrices $A, B$."),
    ("Invertible Matrix Theorem",
     "A square matrix is invertible if and only if its determinant is non-zero."),
    ("Cayley-Hamilton Theorem",
     "Every square matrix over a commutative ring satisfies its own characteristic equation."),
    ("Singular Value Decomposition",
     "Any real or complex matrix admits a decomposition into $U \\Sigma V^*$ with $U, V$ unitary and $\\Sigma$ diagonal of non-negative singular values."),
    ("Intersection of Open Sets",
     "The intersection of a finite collection of open sets is open."),
    ("Union of Open Sets",
     "The union of any collection of open sets is open."),
    ("Heine-Borel Theorem",
     r"A subset of $\mathbb{R}^n$ is compact if and only if it is closed and bounded."),
    ("Continuous Image of Compact Sets",
     "The continuous image of a compact topological space is compact."),
    ("Continuous Image of Connected Sets",
     "The continuous image of a connected topological space is connected."),
    ("Closed Points in Hausdorff Spaces",
     "In a Hausdorff space, every singleton set is closed."),
    ("Tychonoff's Theorem",
     "The product of any collection of compact spaces is compact in the product topology."),
    ("Urysohn's Lemma",
     "Any two disjoint closed subsets of a normal space can be separated by a continuous function to $[0,1]$."),
    ("Brouwer Fixed-Point Theorem",
     "Every continuous function from a convex compact subset of a Euclidean space to itself has a fixed point."),
    ("Cauchy's Integral Theorem",
     "If $f$ is analytic within and on a simple closed contour $C$, then $\\oint_C f(z)\\,dz = 0$."),
    ("Cauchy's Integral Formula",
     "The value of an analytic function inside a simple closed contour is fully determined by its values on the contour."),
    ("Liouville's Theorem",
     "Every entire function that is bounded must be constant."),
    ("Fundamental Theorem of Algebra",
     "Every non-constant single-variable polynomial with complex coefficients has at least one complex root."),
    ("Morera's Theorem",
     "If a continuous function on an open set has vanishing line integral along every closed contour, it is analytic."),
    ("Residue Theorem",
     "The contour integral of a meromorphic function over a simple closed curve equals $2\\pi i$ times the sum of residues inside."),
    ("Law of Large Numbers",
     "The sample mean of i.i.d. random variables with finite mean converges to the expected value as the sample size grows."),
    ("Central Limit Theorem",
     "The normalized sum of i.i.d. random variables with finite variance converges in distribution to a standard normal."),
    ("Markov's Inequality",
     "For a non-negative random variable $X$ and $a > 0$, $P(X \\ge a) \\le E[X]/a$."),
    ("Chebyshev's Inequality",
     "For any random variable with finite variance and any $k > 0$, $P(|X - E[X]| \\ge k \\sigma) \\le 1/k^2$."),
    ("Bayes' Theorem",
     r"$P(A|B) = P(B|A) P(A) / P(B)$ when $P(B) > 0$."),
    ("Picard-Lindelof Theorem",
     "A first-order ODE with a Lipschitz-continuous right-hand side has a unique local solution to any initial-value problem."),
    ("Pythagorean Theorem",
     "In a right triangle, the square of the hypotenuse equals the sum of squares of the other two sides: $a^2 + b^2 = c^2$."),
    ("Area of a Circle",
     "The area of a circle with radius $r$ is $A = \\pi r^2$."),
    ("Circumference of a Circle",
     "The circumference of a circle with radius $r$ is $C = 2 \\pi r$."),
    ("Euler's Polyhedron Formula",
     "For any convex polyhedron, $V - E + F = 2$."),
    ("Stokes' Theorem",
     "The integral of the curl of a vector field over a surface equals the line integral of the field over the boundary."),
]


# Common fallacies — expanded from 18 to 50+ (each will get ~10 variants)
COMMON_FALLACIES = [
    # (wrong_statement, correct_statement, hint_for_teacher)
    ("Every continuous function is differentiable.",
     "Every differentiable function is continuous.",
     "Reverses implication. Weierstrass function is continuous everywhere but differentiable nowhere."),
    ("If $f'(c) = 0$ then $c$ is a local extremum.",
     "If $f$ has a local extremum at $c$ and is differentiable there, then $f'(c) = 0$.",
     "Converse of Fermat's theorem. $f(x)=x^3$ at $0$ is a counterexample."),
    ("The sum of two periodic functions is periodic.",
     "The sum of two continuous periodic functions is periodic if and only if the ratio of their periods is rational.",
     "$\\sin(x) + \\sin(\\pi x)$ is not periodic."),
    ("If a series converges, it converges absolutely.",
     "If a series converges absolutely, then it converges.",
     "Alternating harmonic series converges but not absolutely."),
    ("L'Hôpital's rule applies to $\\infty - \\infty$.",
     "L'Hôpital's Rule applies to indeterminate forms $0/0$ or $\\infty/\\infty$.",
     "$\\infty-\\infty$ must be algebraically rewritten first."),
    ("Every matrix is diagonalizable.",
     "A matrix is diagonalizable iff for every eigenvalue, its algebraic multiplicity equals its geometric multiplicity.",
     "Nilpotent $\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$ is not."),
    ("If $\\det(A) = 0$ then $A$ is the zero matrix.",
     "$\\det(A) = 0$ iff $A$ is singular (non-invertible).",
     "$\\begin{pmatrix}1&0\\\\0&0\\end{pmatrix}$ has det 0 but is not zero."),
    ("Matrix multiplication commutes.",
     "Matrix multiplication is in general non-commutative.",
     "Trivial counterexamples for $2\\times 2$ matrices."),
    ("Eigenvectors of the same eigenvalue are orthogonal.",
     "Eigenvectors from distinct eigenvalues of a real symmetric matrix are orthogonal.",
     "Same-eigenvalue eigenvectors span an eigenspace; orthogonality is a choice."),
    ("Every subgroup of a group is normal.",
     "Every subgroup of an abelian group is normal.",
     "$S_3$ has non-normal subgroups."),
    ("Every field has characteristic zero.",
     "The characteristic of a field is either $0$ or a prime $p$.",
     "$\\mathbb{F}_p$ has characteristic $p$."),
    ("Uncorrelated random variables are always independent.",
     "If two random variables are independent, they are uncorrelated.",
     "Take $X \\sim U[-1,1]$ and $Y = X^2$."),
    ("$E[XY] = E[X]E[Y]$ for any random variables.",
     "$E[XY] = E[X]E[Y]$ holds iff $X$ and $Y$ are uncorrelated.",
     "Positive covariance breaks it."),
    ("If a graph has an Eulerian circuit, it has a Hamiltonian cycle.",
     "Existence of an Eulerian circuit does not imply existence of a Hamiltonian cycle.",
     "Two triangles sharing one vertex: Eulerian, not Hamiltonian."),
    ("Every compact space is metrizable.",
     "Every regular second-countable Hausdorff space is metrizable (Urysohn).",
     "The long line is compact but not metrizable."),
    ("A topological space is compact iff every sequence has a convergent subsequence.",
     "A metric space is compact iff it is sequentially compact.",
     "Equivalence is metric-only."),
    ("Cartesian products of connected spaces under the box topology are connected.",
     "Cartesian products of connected spaces are connected under the product topology.",
     "Box topology breaks this."),
    ("Every bounded function attains its supremum.",
     "Every continuous function on a closed bounded interval attains its supremum.",
     "$f(x)=x$ on $(0,1)$ does not attain $1$."),
    ("All continuous functions are uniformly continuous.",
     "Every continuous function on a closed and bounded interval is uniformly continuous.",
     "$f(x)=1/x$ on $(0,1]$ is continuous but not uniformly continuous."),
    ("Every Cauchy sequence converges.",
     "Every Cauchy sequence in a complete metric space converges.",
     "$\\mathbb{Q}$ is not complete."),
    ("If $\\lim a_n = 0$ then $\\sum a_n$ converges.",
     "$\\lim a_n = 0$ is necessary but not sufficient for $\\sum a_n$ to converge.",
     "Harmonic series."),
    ("$\\sin x$ is uniformly Lipschitz with constant 0.",
     "$\\sin x$ is Lipschitz with constant $1$.",
     "$|\\sin x - \\sin y| \\le |x-y|$."),
    ("If $f$ and $g$ are integrable, $fg$ is integrable.",
     "If $f$ and $g$ are bounded and Riemann integrable on $[a,b]$, then $fg$ is Riemann integrable on $[a,b]$.",
     "Boundedness matters; for Lebesgue use $L^2$ Cauchy-Schwarz."),
    ("$0.999\\ldots < 1$.",
     "$0.999\\ldots = 1$.",
     "Standard limit of geometric series."),
    ("$\\sqrt{a^2} = a$ for all real $a$.",
     "$\\sqrt{a^2} = |a|$ for all real $a$.",
     "Negative inputs flip sign."),
    ("$(a+b)^2 = a^2 + b^2$.",
     "$(a+b)^2 = a^2 + 2ab + b^2$.",
     "Cross term."),
    ("$\\log(a+b) = \\log a + \\log b$.",
     "$\\log(ab) = \\log a + \\log b$.",
     "Confuses sum and product."),
    ("All primes are odd.",
     "$2$ is the only even prime; all other primes are odd.",
     "Edge case at 2."),
    ("$\\mathbb{Z}/n\\mathbb{Z}$ is always a field.",
     "$\\mathbb{Z}/n\\mathbb{Z}$ is a field iff $n$ is prime.",
     "Composite $n$ has zero divisors."),
    ("Every group of order $n$ is cyclic.",
     "Every group of prime order is cyclic.",
     "Klein four-group has order 4 and is not cyclic."),
    ("Every linear map is injective.",
     "A linear map between finite-dimensional spaces is injective iff its kernel is trivial.",
     "Projections kill subspaces."),
    ("The image of a basis under a linear map is a basis.",
     "The image of a basis under an injective linear map is a basis of the image.",
     "Without injectivity, image vectors may be dependent."),
    ("If $A^2 = 0$ then $A = 0$.",
     "If $A$ is real symmetric and $A^2 = 0$, then $A = 0$.",
     "Nilpotent counterexample $\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$."),
    ("$\\det(A+B) = \\det A + \\det B$.",
     "Determinants are not additive in general; only $\\det(AB) = \\det A \\det B$.",
     "Pick any 2x2 example."),
    ("If $f: \\mathbb{R} \\to \\mathbb{R}$ is bijective and continuous, then $f^{-1}$ is continuous.",
     "If $f: \\mathbb{R} \\to \\mathbb{R}$ is continuous and bijective, then $f$ is strictly monotonic and $f^{-1}$ is continuous.",
     "Need to invoke monotonicity."),
    ("If $f$ is integrable, $f$ is continuous.",
     "If $f$ is continuous on $[a,b]$, $f$ is Riemann integrable on $[a,b]$.",
     "Reverses direction; step functions are integrable but not continuous."),
    ("If $f$ is differentiable, $f'$ is continuous.",
     "Differentiability of $f$ does not imply continuity of $f'$ (only continuous differentiability does).",
     "$f(x) = x^2 \\sin(1/x)$ extended to 0."),
    ("In probability, $P(A \\cup B) = P(A) + P(B)$.",
     "$P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$; equality holds iff $A,B$ are disjoint.",
     "Inclusion-exclusion."),
    ("$P(A|B) = P(B|A)$.",
     "$P(A|B) = P(A \\cap B)/P(B)$, which is generally not $P(B|A)$.",
     "Bayes confusion."),
    ("If $X,Y$ are normal, then $X+Y$ is normal.",
     "If $X,Y$ are jointly normal, then $X+Y$ is normal.",
     "Marginal normality is insufficient."),
    ("Every smooth function is analytic.",
     "Every analytic function is smooth, but not conversely (e.g., $e^{-1/x^2}$).",
     "Smooth ≠ analytic; flat-bump function."),
    ("The set of irrationals is countable.",
     "The set of rationals is countable; the set of irrationals is uncountable.",
     "Cantor's argument."),
    ("Every infinite set has the same cardinality.",
     "$|\\mathbb{N}| < |\\mathbb{R}|$; infinite sets can have distinct cardinalities.",
     "Cantor's diagonal."),
    ("$\\mathbb{R}$ is countable.",
     "$\\mathbb{R}$ is uncountable.",
     "Diagonal argument."),
    ("Every group homomorphism is injective.",
     "A group homomorphism is injective iff its kernel is trivial.",
     "Reduction modulo n is a non-injective homomorphism."),
    ("If $G$ is abelian, every subgroup is cyclic.",
     "Every subgroup of a cyclic group is cyclic.",
     "$\\mathbb{Z}/2 \\times \\mathbb{Z}/2$ is abelian, not cyclic."),
    ("Compact subsets of any topological space are closed.",
     "Compact subsets of a Hausdorff space are closed.",
     "Non-Hausdorff counterexamples exist."),
    ("Every connected space is path-connected.",
     "Every path-connected space is connected; the converse fails (topologist's sine curve).",
     "Path-connectedness is strictly stronger."),
    ("If $f$ is continuous and $f' \\ge 0$ then $f$ is non-decreasing on its domain.",
     "If $f$ is continuous on $[a,b]$ and differentiable on $(a,b)$ with $f' \\ge 0$, then $f$ is non-decreasing on $[a,b]$.",
     "Need differentiability hypothesis explicit."),
    ("Every monotone function is differentiable.",
     "A monotone function on a closed interval is differentiable almost everywhere (Lebesgue).",
     "Cantor function is monotone but $f'=0$ a.e."),
    ("Compactness implies finiteness.",
     "Compactness does not imply finiteness; $[0,1]$ is compact but uncountable.",
     "Cardinality has no relation."),
]

# --------------------------------------------------------------------------- #
# Garbling / variant generation
# --------------------------------------------------------------------------- #

def informalize(text: str, rng: random.Random) -> str:
    rep = {
        "continuous function": "continuous",
        "differentiable function": "diff function",
        "differentiable": "diff",
        "converges uniformly": "converges",
        "uniformly continuous": "continuous",
        "absolute value": "mod",
        "if and only if": "iff",
        "for all": "every",
        "there exists": "has",
        "such that": "st",
        "implies": "->",
        "subset of": "in",
        "non-empty": "nonempty",
    }
    for k, v in rep.items():
        if rng.random() < 0.4:
            text = text.replace(k, v)
    return text


def drop_conditions(text: str, rng: random.Random) -> str:
    conds = ["closed ", "bounded ", "compact ", "finite ",
             "absolutely ", "uniformly ", "non-empty ",
             "connected ", "open ", "continuous "]
    for c in conds:
        if c in text and rng.random() < 0.5:
            text = text.replace(c, "", 1)
    return text


def garble(text: str, rng: random.Random) -> str:
    chars = list(text)
    n = max(1, int(len(chars) * rng.uniform(0.04, 0.12)))
    pool = "abcdefghijklmnopqrstuvwxyz0123456789$%^&*()_+-=[]{}|;':,./<>?"
    for _ in range(n):
        idx = rng.randint(0, len(chars) - 1)
        chars[idx] = rng.choice(pool)
    return "".join(chars)


def make_bad_note(stmt: str, rng: random.Random, mode: str = "auto") -> str:
    """mode: auto / informal / drop / garble / lower / preserve"""
    bad = stmt
    if mode == "preserve":
        return bad
    if mode == "auto":
        if rng.random() < 0.55:
            bad = informalize(bad, rng)
        if rng.random() < 0.45:
            bad = drop_conditions(bad, rng)
        if rng.random() < 0.35:
            bad = bad.lower().replace(".", "")
        if rng.random() < 0.25:
            bad = garble(bad, rng)
    elif mode == "garble":
        bad = garble(bad, rng)
    elif mode == "drop":
        bad = drop_conditions(bad, rng)
    elif mode == "informal":
        bad = informalize(bad, rng)
    elif mode == "lower":
        bad = bad.lower().replace(".", "")
    return bad


def wrap_with_conversation(stmt: str, rng: random.Random) -> tuple[str, str, str]:
    """Returns (prefix, body, suffix)"""
    prefix = rng.choice(WRAPPERS_PREFIX)
    suffix = rng.choice(WRAPPERS_SUFFIX)
    return prefix, stmt, suffix


# --------------------------------------------------------------------------- #
# Teacher model
# --------------------------------------------------------------------------- #

TEACHER_TASK_PROMPT = """Fix the math. Format strictly:
<think>
2 concise rationale sentences. Start sentence 1 with a distinctive phrase from this exact theorem or student wording, not a generic phrase like "The student's statement". Say what theorem ({theorem_name}), what's wrong, why (use because/however/since/actually).
</think>
{prefix}{reference}{suffix}

Student wrote: {bad_note}
Correct form to output: {reference}"""

TEACHER_NONMATH_PROMPT = """User said: "{query}"
Not math. Output exactly:
<think>
This isn't math because it's a casual query, so no theorem needs correction.
</think>
(No mathematical theorem detected.)"""

TEACHER_ALREADY_CORRECT_PROMPT = """The statement below is correct. Output exactly:
<think>
Correct: matches {theorem_name} since all conditions are present, so no change needed.
</think>
{prefix}{good_note}{suffix}

Statement: {good_note}"""


def load_teacher(path: str):
    print(f"[INFO] Loading teacher tokenizer from {path}")
    tok = AutoTokenizer.from_pretrained(path, trust_remote_code=True)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token

    print("[INFO] Configuring 4-bit (NF4) quantization for teacher")
    bnb = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
        bnb_4bit_use_double_quant=True,
    )
    print(f"[INFO] Loading teacher model from {path} (~30s)")
    t0 = time.time()
    model = AutoModelForCausalLM.from_pretrained(
        path, quantization_config=bnb, device_map="auto",
        trust_remote_code=True,
    )
    model.eval()
    print(f"[INFO] Teacher loaded in {time.time() - t0:.1f}s")
    return model, tok


def teacher_generate(model, tok, user_prompt: str,
                     temperature: float = 0.7, max_new_tokens: int = 384,
                     do_sample: bool = True) -> tuple[str, int]:
    """Returns (generated_text, num_new_tokens) for tok/s tracking."""
    messages = [{"role": "user", "content": user_prompt}]
    text = tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tok(text, return_tensors="pt").to(model.device)
    gen_kwargs = dict(
        max_new_tokens=max_new_tokens,
        eos_token_id=tok.eos_token_id,
        pad_token_id=tok.pad_token_id,
        use_cache=True,
    )
    if do_sample:
        gen_kwargs.update(do_sample=True, temperature=temperature, top_p=0.9, repetition_penalty=1.05)
    else:
        gen_kwargs.update(do_sample=False)
    with torch.no_grad():
        out = model.generate(**inputs, **gen_kwargs)
    gen = out[0][inputs.input_ids.shape[1]:]
    return tok.decode(gen, skip_special_tokens=True), int(gen.shape[0])


OPENAI_TEACHER_SYSTEM = """You generate compact supervised fine-tuning records for a mathematical theorem correction model.
Return only the requested text. The <think> block must contain a brief rationale summary, not private hidden reasoning.
Avoid generic openings; make the first 80 characters of the rationale specific to the theorem or the student's wording."""


def openai_generate(user_prompt: str, model: str,
                    base_url: str = "https://token-plan-sgp.xiaomimimo.com/v1",
                    timeout: int = 120,
                    max_output_tokens: int = 768,
                    http_retries: int = 5,
                    **_: object) -> tuple[str, int]:
    """Call an OpenAI-compatible Chat Completions endpoint.

    Returns (text, num_tokens) where `text` is shaped like:
        <think>
        {reasoning_content from API}
        </think>
        {content from API}

    Works with:
      * OpenAI-compatible reasoning models that expose `reasoning_content`
        in the response (e.g. xiaomi MiMo's mimo-v2.5-pro).
      * Plain Chat Completions models (no reasoning field) — in that case
        we expect the model to emit <think>...</think> tags inside `content`
        on its own (rare; mostly produces a fallback).
    """
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set")

    endpoint = base_url.rstrip("/") + "/chat/completions"
    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": OPENAI_TEACHER_SYSTEM},
            {"role": "user", "content": user_prompt},
        ],
        "max_tokens": max_output_tokens,
        "temperature": 0.6,
        "top_p": 0.9,
    }
    data = json.dumps(body).encode("utf-8")
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    last_error = None
    for attempt in range(http_retries):
        req = urllib.request.Request(endpoint, data=data, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                payload = json.loads(resp.read().decode("utf-8"))
            choices = payload.get("choices") or []
            if not choices:
                last_error = f"empty choices: {str(payload)[:300]}"
                time.sleep(min(2 ** attempt, 30))
                continue
            msg = choices[0].get("message") or {}
            content = (msg.get("content") or "").strip()
            reasoning = (msg.get("reasoning_content") or "").strip()

            if reasoning:
                # API gave us thinking separately — wrap in our format
                text = f"<think>\n{reasoning}\n</think>\n{content}"
            else:
                # Model put everything in content; hopefully it has <think> tags
                text = content

            usage = payload.get("usage", {}) or {}
            tokens = (
                usage.get("completion_tokens")
                or usage.get("output_tokens")
                or max(len(text) // 4, 1)
            )
            return text, int(tokens)
        except urllib.error.HTTPError as e:
            detail = e.read().decode("utf-8", errors="replace")
            last_error = f"HTTP {e.code}: {detail[:500]}"
            if e.code not in (408, 409, 429, 500, 502, 503, 504):
                break
        except Exception as e:
            last_error = repr(e)
        time.sleep(min(2 ** attempt, 30))

    raise RuntimeError(f"OpenAI API request failed after {http_retries} attempts: {last_error}")


# --------------------------------------------------------------------------- #
# Quality filtering & extraction
# --------------------------------------------------------------------------- #

THINK_RE = re.compile(r"<think>(.*?)</think>", re.DOTALL)


def extract_think_and_answer(text: str) -> tuple[str | None, str | None]:
    """Returns (think_content, answer_after_think). Either may be None on failure."""
    m = THINK_RE.search(text)
    if not m:
        return None, None
    think = m.group(1).strip()
    answer = text[m.end():].strip()
    return think, answer


def passes_quality(think: str | None, answer: str | None,
                   require_keywords: bool = True) -> tuple[bool, str]:
    if think is None:
        return False, "no_think_block"
    if answer is None or not answer.strip():
        return False, "no_answer"
    if len(think) < 30:
        return False, "think_too_short"
    if len(think) > 4000:
        return False, "think_too_long"
    if require_keywords:
        low = think.lower()
        if not any(kw in low for kw in THINK_QUALITY_KEYWORDS):
            return False, "no_quality_keyword"
    # Reject the old boilerplate template explicitly
    if "rigorous form is" in think and "imprecise shorthand" in think:
        return False, "boilerplate_template"
    if len(answer) > 800:
        return False, "answer_too_long"
    return True, "ok"


def build_record(bad_note_full: str, think: str, answer: str) -> dict:
    return {
        "instruction": SYSTEM_PROMPT,
        "input": bad_note_full,
        "output": f"<think>\n{think}\n</think>\n{answer}",
    }


# --------------------------------------------------------------------------- #
# Source filtering
# --------------------------------------------------------------------------- #

def is_usable_wiki_theorem(stmt: str) -> bool:
    """Filter wikipedia entries: keep statement-like, not descriptive paragraphs."""
    if not stmt:
        return False
    L = len(stmt)
    if L < 30 or L > 500:
        return False
    # Heuristic: theorem statements contain math indicators or short verbs
    indicators = ["$", "if ", "iff", "every", "for all", "there exists",
                  "implies", "is a", "is the", "equals", "=", "\\", "theorem"]
    if not any(i in stmt.lower() for i in indicators):
        return False
    # Drop long descriptive paragraphs
    if stmt.count(". ") > 4:
        return False
    return True


# --------------------------------------------------------------------------- #
# Job planning
# --------------------------------------------------------------------------- #

def plan_jobs(target: int, rng: random.Random) -> list[dict]:
    """
    Build the full job queue. Each job is a dict describing what kind of
    sample to generate. Mix is calibrated to the target size.
    """
    fractions = {
        "wiki": 0.50,
        "base_theorem": 0.10,
        "fallacy": 0.10,
        "already_correct": 0.20,
        "non_math": 0.05,
        "ambiguous": 0.05,
    }
    counts = {k: int(target * v) for k, v in fractions.items()}
    # Round any leftover to wiki
    counts["wiki"] += target - sum(counts.values())

    jobs = []

    # Load wiki theorems
    wiki_path = "data/wikipedia_theorems.json"
    wiki = []
    if os.path.exists(wiki_path):
        with open(wiki_path, "r", encoding="utf-8") as f:
            for w in json.load(f):
                if is_usable_wiki_theorem(w.get("statement", "")):
                    wiki.append(w)
    print(f"[INFO] Filtered wiki theorems: {len(wiki)} usable / target {counts['wiki']} jobs")

    if wiki:
        for _ in range(counts["wiki"]):
            w = rng.choice(wiki)
            jobs.append({
                "kind": "correction",
                "name": w["name"][:80],
                "stmt": w["statement"],
                "mode": rng.choice(["auto", "auto", "drop", "informal", "garble", "lower"]),
            })

    for _ in range(counts["base_theorem"]):
        name, stmt = rng.choice(BASE_THEOREMS)
        jobs.append({
            "kind": "correction",
            "name": name,
            "stmt": stmt,
            "mode": rng.choice(["auto", "auto", "drop", "informal", "garble"]),
        })

    for _ in range(counts["fallacy"]):
        wrong, correct, hint = rng.choice(COMMON_FALLACIES)
        jobs.append({
            "kind": "fallacy",
            "wrong": wrong,
            "correct": correct,
            "hint": hint,
        })

    if wiki:
        for _ in range(counts["already_correct"]):
            w = rng.choice(wiki)
            jobs.append({
                "kind": "already_correct",
                "name": w["name"][:80],
                "stmt": w["statement"],
            })
    else:
        for _ in range(counts["already_correct"]):
            name, stmt = rng.choice(BASE_THEOREMS)
            jobs.append({"kind": "already_correct", "name": name, "stmt": stmt})

    for _ in range(counts["non_math"]):
        jobs.append({"kind": "non_math", "query": rng.choice(NON_MATH_QUERIES)})

    # Ambiguous: take a base theorem, truncate it to make it ambiguous
    for _ in range(counts["ambiguous"]):
        name, stmt = rng.choice(BASE_THEOREMS)
        words = stmt.split()
        keep = max(3, int(len(words) * rng.uniform(0.3, 0.6)))
        truncated = " ".join(words[:keep])
        jobs.append({
            "kind": "correction",
            "name": name,
            "stmt": stmt,
            "mode": "preserve",
            "override_bad": truncated,
        })

    rng.shuffle(jobs)
    print(f"[INFO] Planned {len(jobs)} jobs: " +
          " ".join(f"{k}={v}" for k, v in counts.items()))
    return jobs


# --------------------------------------------------------------------------- #
# Main loop
# --------------------------------------------------------------------------- #

def run_job(job: dict, rng: random.Random, generate_fn,
            max_retries: int = 3,
            use_reference_answer: bool = False) -> dict | None:
    """Returns a built record or None if all attempts fail."""
    expected_answer = None
    if job["kind"] in ("correction",):
        prefix, body, suffix = wrap_with_conversation("", rng)
        if "override_bad" in job:
            bad = job["override_bad"]
        else:
            bad = make_bad_note(job["stmt"], rng, mode=job.get("mode", "auto"))
        bad_full = f"{prefix}{bad}{suffix}".strip()
        good_full = f"{prefix}{job['stmt']}{suffix}".strip()
        expected_answer = good_full
        prompt = TEACHER_TASK_PROMPT.format(
            theorem_name=job["name"],
            reference=job["stmt"],
            bad_note=bad,
            prefix=prefix,
            suffix=suffix,
        )
        require_kw = True
    elif job["kind"] == "fallacy":
        prefix, body, suffix = wrap_with_conversation("", rng)
        bad = job["wrong"]
        if rng.random() < 0.2:
            bad = garble(bad, rng)
        bad_full = f"{prefix}{bad}{suffix}".strip()
        expected_answer = f"{prefix}{job['correct']}{suffix}".strip()
        prompt = TEACHER_TASK_PROMPT.format(
            theorem_name="Common Fallacy",
            reference=f"{job['correct']} (Hint: {job['hint']})",
            bad_note=bad,
            prefix=prefix,
            suffix=suffix,
        )
        require_kw = True
    elif job["kind"] == "already_correct":
        prefix, body, suffix = wrap_with_conversation("", rng)
        good_full = f"{prefix}{job['stmt']}{suffix}".strip()
        bad_full = good_full
        expected_answer = good_full
        prompt = TEACHER_ALREADY_CORRECT_PROMPT.format(
            theorem_name=job["name"],
            good_note=job["stmt"],
            prefix=prefix,
            suffix=suffix,
        )
        require_kw = False  # already-correct samples may have shorter think
    elif job["kind"] == "non_math":
        bad_full = job["query"]
        expected_answer = "(No mathematical theorem detected.)"
        prompt = TEACHER_NONMATH_PROMPT.format(query=job["query"])
        require_kw = False
    else:
        return None

    last_reason = "no_attempt"
    last_tokens = 0
    last_raw = ""
    for attempt in range(max_retries):
        # Attempt 0: fast greedy. Attempts 1+: sample with rising temp.
        do_sample = attempt > 0
        temp = 0.6 + 0.2 * attempt
        try:
            raw, n_tok = generate_fn(
                prompt,
                temperature=temp, do_sample=do_sample,
            )
            last_tokens = n_tok
            last_raw = raw
        except Exception as e:
            print(f"  [WARN] generation error (attempt {attempt + 1}): {e}")
            continue
        think, answer = extract_think_and_answer(raw)
        ok, reason = passes_quality(think, answer, require_keywords=require_kw)
        last_reason = reason
        if ok:
            if use_reference_answer and expected_answer:
                answer = expected_answer
            return (build_record(bad_full, think, answer), n_tok, attempt + 1, "ok", "")
    return (None, last_tokens, max_retries, last_reason, last_raw[:300])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--teacher-provider", choices=["local", "openai"], default="local",
                        help="Use local HF teacher or OpenAI API teacher.")
    parser.add_argument("--teacher", default="models/Qwen2.5-7B-Instruct",
                        help="Teacher model directory. Default: Qwen2.5-7B-Instruct (faster on 8GB GPU). "
                             "Use models/DeepSeek-R1-Distill-Qwen-7B for higher-quality CoT but ~10x slower.")
    parser.add_argument("--openai-model", default="mimo-v2.5-pro",
                        help="API model used when --teacher-provider=openai. "
                             "Default: mimo-v2.5-pro (xiaomi reasoning model with reasoning_content).")
    parser.add_argument("--openai-base-url", default=os.environ.get("OPENAI_BASE_URL", "https://token-plan-sgp.xiaomimimo.com/v1"),
                        help="OpenAI-compatible API base URL.")
    parser.add_argument("--api-workers", type=int, default=8,
                        help="Concurrent API workers for --teacher-provider=openai.")
    parser.add_argument("--api-timeout", type=int, default=120,
                        help="Per-request API timeout in seconds.")
    parser.add_argument("--api-http-retries", type=int, default=5,
                        help="HTTP retries for transient API errors.")
    parser.add_argument("--quality-retries", type=int, default=3,
                        help="Regenerate a sample this many times if quality filters fail.")
    parser.add_argument("--save-every", type=int, default=10,
                        help="Write partial file after this many accepted records.")
    parser.add_argument("--use-reference-answer", action="store_true",
                        help="Use the script's known corrected answer instead of the teacher answer.")
    parser.add_argument("--target", type=int, default=3000,
                        help="Number of samples to generate. Default 3000 (~3-5 hours on 8GB).")
    parser.add_argument("--output", default="data/student_notes_train_v2.json")
    parser.add_argument("--partial", default="data/student_notes_train_v2_partial.json")
    parser.add_argument("--stats", default="data/student_notes_train_v2_stats.txt")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--dry-run", action="store_true",
                        help="Generate --num samples then exit (smoke test)")
    parser.add_argument("--num", type=int, default=5,
                        help="Number of samples for --dry-run")
    parser.add_argument("--verbose", action="store_true",
                        help="Print full failure reason and partial generation when a sample fails")
    args = parser.parse_args()

    rng = random.Random(args.seed)
    use_reference_answer = args.use_reference_answer or args.teacher_provider == "openai"

    if args.teacher_provider == "local":
        if not os.path.exists(args.teacher):
            print(f"[FATAL] Teacher model not found: {args.teacher}")
            print("[HINT] Download with:")
            print("  huggingface-cli download deepseek-ai/DeepSeek-R1-Distill-Qwen-7B \\")
            print(f"    --local-dir {args.teacher}")
            print("  (or set HF_ENDPOINT=https://hf-mirror.com if HF is blocked)")
            sys.exit(1)

        model, tok = load_teacher(args.teacher)

        def generate_fn(prompt: str, **kwargs):
            return teacher_generate(model, tok, prompt, **kwargs)
    else:
        if not os.environ.get("OPENAI_API_KEY"):
            print("[FATAL] OPENAI_API_KEY is not set; cannot use --teacher-provider=openai")
            sys.exit(1)
        print(f"[INFO] Using OpenAI teacher model: {args.openai_model}")
        print(f"[INFO] API workers: {args.api_workers}")

        def generate_fn(prompt: str, **kwargs):
            return openai_generate(
                prompt,
                model=args.openai_model,
                base_url=args.openai_base_url,
                timeout=args.api_timeout,
                http_retries=args.api_http_retries,
                **kwargs,
            )

    if args.dry_run:
        print(f"\n[DRY RUN] Generating {args.num} samples")
        jobs = plan_jobs(args.num, rng)[:args.num]
        for i, job in enumerate(jobs):
            print(f"\n--- Job {i + 1}/{len(jobs)}: kind={job['kind']} ---")
            t0 = time.time()
            rec, n_tok, attempts, reason, partial = run_job(
                job, rng, generate_fn,
                max_retries=args.quality_retries,
                use_reference_answer=use_reference_answer,
            )
            dt = time.time() - t0
            tps = n_tok / dt if dt > 0 else 0
            if rec:
                print(f"  [OK] {dt:.1f}s  {n_tok} tok  {tps:.1f} tok/s  attempts={attempts}")
                print(f"  INPUT:  {rec['input'][:120]}")
                print(f"  OUTPUT: {rec['output'][:300]}")
            else:
                print(f"  [FAIL] {dt:.1f}s  {n_tok} tok  reason={reason}")
                print(f"  Partial generation (first 300 chars): {partial!r}")
        print("\n[DRY RUN DONE]")
        return

    # Resume support
    completed = []
    if os.path.exists(args.partial):
        try:
            with open(args.partial, "r", encoding="utf-8") as f:
                completed = json.load(f)
            print(f"[RESUME] Loaded {len(completed)} previously completed records")
        except Exception as e:
            print(f"[WARN] Could not parse {args.partial}: {e}. Starting fresh.")

    if len(completed) >= args.target:
        print(f"[INFO] Already have {len(completed)} >= target {args.target}. "
              f"Writing to {args.output} and exiting.")
        with open(args.output, "w", encoding="utf-8") as f:
            json.dump(completed[:args.target], f, ensure_ascii=False, indent=2)
        write_stats(completed[:args.target], args.stats)
        return

    remaining = args.target - len(completed)
    print(f"[INFO] Need {remaining} more samples (have {len(completed)} / target {args.target})")
    jobs = plan_jobs(remaining, rng)

    fail_counts = Counter()
    t_start = time.time()
    total_tokens = 0
    saved_since_partial = 0

    def save_partial():
        with open(args.partial, "w", encoding="utf-8") as f:
            json.dump(completed, f, ensure_ascii=False, indent=2)

    for i, job in enumerate(jobs, start=1):
        t0 = time.time()
        rec, n_tok, attempts, reason, partial = run_job(
            job, rng, generate_fn,
            max_retries=args.quality_retries,
            use_reference_answer=use_reference_answer,
        )
        dt = time.time() - t0
        total_tokens += n_tok
        tps = n_tok / dt if dt > 0 else 0
        status = "OK" if rec else "FAIL"
        retry_tag = f" retry={attempts}" if attempts > 1 else ""
        fail_tag = f" reason={reason}" if not rec else ""
        # Per-sample heartbeat — confirms the script is alive between batch reports
        print(f"  [{i}/{len(jobs)} {status}] {job['kind']:14s} {dt:5.1f}s "
              f"{n_tok:4d}tok {tps:5.1f}tok/s{retry_tag}{fail_tag}", flush=True)
        if not rec and args.verbose:
            print(f"    partial: {partial!r}")

        if rec:
            completed.append(rec)
            saved_since_partial += 1
        else:
            fail_counts[job["kind"]] += 1

        # Periodic summary + persistence
        if i % 25 == 0 or i == len(jobs):
            elapsed = time.time() - t_start
            rate = i / max(elapsed, 1e-3)
            eta = (len(jobs) - i) / max(rate, 1e-3)
            avg_tps = total_tokens / max(elapsed, 1e-3)
            print(f"=== [{i}/{len(jobs)}] kept={len(completed)} "
                  f"failed={sum(fail_counts.values())} "
                  f"rate={rate * 60:.1f}samples/min "
                  f"avg={avg_tps:.1f}tok/s "
                  f"eta={eta / 60:.0f}min ===", flush=True)
        if saved_since_partial >= max(args.save_every, 1):
            save_partial()
            saved_since_partial = 0

    if saved_since_partial:
        save_partial()

    # Final write
    print(f"\n[INFO] Done. Total kept: {len(completed)}")
    if fail_counts:
        print(f"[INFO] Failures by kind: {dict(fail_counts)}")
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(completed, f, ensure_ascii=False, indent=2)
    print(f"[OK] Wrote {args.output}")
    write_stats(completed, args.stats)
    # Keep partial as backup until next run
    print(f"[INFO] Partial file kept at {args.partial} (delete manually if desired)")


def write_stats(records: list[dict], path: str):
    """Diagnostic report for the user to verify dataset quality."""
    n = len(records)
    if n == 0:
        return
    think_blocks = []
    answer_blocks = []
    for r in records:
        out = r["output"]
        m = THINK_RE.search(out)
        if m:
            think_blocks.append(m.group(1).strip())
            answer_blocks.append(out[m.end():].strip())
        else:
            answer_blocks.append(out.strip())

    unique_think = len({t[:80] for t in think_blocks})
    avg_think = sum(len(t) for t in think_blocks) / max(len(think_blocks), 1)
    avg_answer = sum(len(a) for a in answer_blocks) / max(len(answer_blocks), 1)

    boilerplate_hits = sum(
        1 for t in think_blocks
        if "rigorous form is" in t and "imprecise shorthand" in t
    )

    prefixes = Counter(r["input"][:25] for r in records)
    top_prefixes = prefixes.most_common(10)

    lines = [
        f"=== student_notes_train_v2 stats ===",
        f"total records: {n}",
        f"records with <think>: {len(think_blocks)} ({len(think_blocks) / n:.1%})",
        f"unique think openings (first 80 chars): {unique_think} "
        f"(diversity ratio: {unique_think / max(len(think_blocks), 1):.3f})",
        f"avg think length: {avg_think:.0f} chars",
        f"avg answer length: {avg_answer:.0f} chars",
        f"old-template hits: {boilerplate_hits} (target: 0)",
        f"",
        f"top 10 input prefixes (templates):",
    ]
    for p, c in top_prefixes:
        lines.append(f"  {c:5d}  {p!r}")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[OK] Stats written to {path}")
    print("\n--- STATS ---")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
